import type { ColorTheme, Palette, SemanticStyle, TextMateRule } from "./types.js";

const transparent = "#00000000";

function workbench(p: Palette): Record<string, string> {
  const dark = p.kind === "dark";
  const chrome = dark ? p.bg : p.accent;
  const chromeForeground = dark ? p.fgMuted : p.accentContrast;
  const dangerBackground = dark ? "#5A1D22" : "#FDE7E7";
  const warningBackground = dark ? "#4D3B12" : "#FFF3CD";
  const infoBackground = dark ? "#173B52" : "#E2F2FF";
  const inserted = dark ? "#3B5D363D" : "#91C78855";
  const removed = dark ? "#7A303A40" : "#E79AA855";

  return {
    "activityBar.activeBackground": dark ? p.bgMuted : "#4D366F",
    "activityBar.activeBorder": dark ? p.accent : "#FFFFFF00",
    "activityBar.activeFocusBorder": dark ? p.accentContrast : "#FFFFFF00",
    "activityBar.background": chrome,
    "activityBar.border": dark ? p.border : "#FFFFFF00",
    "activityBar.dropBorder": dark ? p.accent : "#FFFFFF",
    "activityBar.foreground": chromeForeground,
    "activityBar.inactiveForeground": dark ? p.fgSubtle : "#EDEDED",
    "activityBarBadge.background": dark ? p.accent : "#EDEDED",
    "activityBarBadge.foreground": dark ? p.accentContrast : p.accent,
    "activityBarTop.activeBorder": p.accent,
    "activityBarTop.dropBorder": p.accent,
    "badge.background": p.accent,
    "badge.foreground": p.accentContrast,
    "banner.background": infoBackground,
    "banner.foreground": p.fg,
    "banner.iconForeground": p.blue,
    "breadcrumb.activeSelectionForeground": p.fg,
    "breadcrumb.background": p.bg,
    "breadcrumb.focusForeground": p.fg,
    "breadcrumb.foreground": p.fgMuted,
    "breadcrumbPicker.background": p.bgElevated,
    "button.background": p.accent,
    "button.border": transparent,
    "button.foreground": p.accentContrast,
    "button.hoverBackground": p.accentHover,
    "button.secondaryBackground": p.bgSubtle,
    "button.secondaryForeground": p.fg,
    "button.secondaryHoverBackground": p.border,
    "chat.avatarBackground": p.bgSubtle,
    "chat.avatarForeground": p.fg,
    "chat.checkpointSeparator": p.border,
    "chat.requestBubbleBackground": dark ? "#313136" : "#F0E7FA",
    "chat.requestBubbleHoverBackground": dark ? "#393940" : "#E8DAF5",
    "chat.slashCommandBackground": p.secondarySoft,
    "chat.slashCommandForeground": p.secondary,
    "chat.thinkingShimmer": p.secondary,
    "checkbox.background": p.bgElevated,
    "checkbox.border": p.border,
    "checkbox.foreground": p.fg,
    "commandCenter.activeBackground": dark ? "#FFFFFF18" : "#FFFFFF30",
    "commandCenter.activeBorder": p.accent,
    "commandCenter.activeForeground": chromeForeground,
    "commandCenter.background": dark ? "#FFFFFF0D" : "#FFFFFF1F",
    "commandCenter.border": dark ? p.border : "#FFFFFF66",
    "commandCenter.foreground": chromeForeground,
    "commandCenter.inactiveBorder": dark ? p.border : "#FFFFFF45",
    "commandCenter.inactiveForeground": dark ? p.fgSubtle : "#E2DAEA",
    "debugConsole.errorForeground": p.red,
    "debugConsole.infoForeground": p.blue,
    "debugConsole.sourceForeground": p.purple,
    "debugConsole.warningForeground": p.yellow,
    "debugConsoleInputIcon.foreground": p.secondary,
    "debugExceptionWidget.background": dangerBackground,
    "debugExceptionWidget.border": p.red,
    "debugIcon.breakpointCurrentStackframeForeground": p.yellow,
    "debugIcon.breakpointDisabledForeground": p.fgSubtle,
    "debugIcon.breakpointForeground": p.red,
    "debugIcon.breakpointStackframeForeground": p.green,
    "debugIcon.breakpointUnverifiedForeground": p.fgMuted,
    "debugIcon.continueForeground": p.green,
    "debugIcon.disconnectForeground": p.red,
    "debugIcon.pauseForeground": p.yellow,
    "debugIcon.restartForeground": p.green,
    "debugIcon.startForeground": p.green,
    "debugIcon.stepBackForeground": p.blue,
    "debugIcon.stepIntoForeground": p.blue,
    "debugIcon.stepOutForeground": p.blue,
    "debugIcon.stepOverForeground": p.blue,
    "debugIcon.stopForeground": p.red,
    "debugToolBar.background": p.bgElevated,
    "debugToolBar.border": p.border,
    "descriptionForeground": p.fgMuted,
    "diffEditor.border": p.border,
    "diffEditor.diagonalFill": p.border,
    "diffEditor.insertedLineBackground": inserted,
    "diffEditor.insertedTextBackground": dark ? "#72A86B55" : "#5A9B5055",
    "diffEditor.removedLineBackground": removed,
    "diffEditor.removedTextBackground": dark ? "#C75C6955" : "#C94D6155",
    "diffEditor.unchangedCodeBackground": dark ? "#FFFFFF08" : "#00000008",
    "diffEditor.unchangedRegionBackground": p.bgMuted,
    "diffEditor.unchangedRegionForeground": p.fgMuted,
    "disabledForeground": dark ? "#E7E7E766" : "#3B334766",
    "dropdown.background": p.bgElevated,
    "dropdown.border": p.border,
    "dropdown.foreground": p.fg,
    "dropdown.listBackground": p.bgElevated,
    "editor.background": p.bg,
    "editor.findMatchBackground": dark ? "#EF820C66" : "#F5A62380",
    "editor.findMatchHighlightBackground": p.secondarySoft,
    "editor.findRangeHighlightBackground": dark ? "#FFFFFF10" : "#70569714",
    "editor.focusedStackFrameHighlightBackground": dark ? "#3B5D3655" : "#B8D9AF80",
    "editor.foldBackground": p.secondarySoft,
    "editor.foreground": p.fg,
    "editor.hoverHighlightBackground": p.secondarySoft,
    "editor.inactiveSelectionBackground": p.selectionInactive,
    "editor.inlineValuesBackground": dark ? "#FFFFFF12" : "#70569714",
    "editor.inlineValuesForeground": p.fgMuted,
    "editor.lineHighlightBackground": p.lineHighlight,
    "editor.linkedEditingBackground": p.secondarySoft,
    "editor.rangeHighlightBackground": p.secondarySoft,
    "editor.selectionBackground": p.selection,
    "editor.selectionHighlightBackground": p.secondarySoft,
    "editor.snippetFinalTabstopHighlightBorder": p.accent,
    "editor.snippetTabstopHighlightBackground": p.secondarySoft,
    "editor.symbolHighlightBackground": p.secondarySoft,
    "editor.wordHighlightBackground": dark ? "#82AAFF26" : "#1459B826",
    "editor.wordHighlightStrongBackground": dark ? "#FEDD6E26" : "#8B510026",
    "editor.wordHighlightTextBackground": p.secondarySoft,
    "editorBracketHighlight.foreground1": p.cyan,
    "editorBracketHighlight.foreground2": p.yellow,
    "editorBracketHighlight.foreground3": p.purple,
    "editorBracketHighlight.foreground4": p.green,
    "editorBracketHighlight.foreground5": p.blue,
    "editorBracketHighlight.foreground6": p.orange,
    "editorBracketHighlight.unexpectedBracket.foreground": p.red,
    "editorBracketMatch.background": p.secondarySoft,
    "editorBracketMatch.border": p.secondary,
    "editorCodeLens.foreground": p.fgSubtle,
    "editorCursor.foreground": dark ? "#FFCC00" : "#4E342E",
    "editorError.foreground": p.red,
    "editorGhostText.background": transparent,
    "editorGhostText.border": transparent,
    "editorGhostText.foreground": dark ? "#E7E7E766" : "#3B334766",
    "editorGroup.border": p.border,
    "editorGroup.dropBackground": p.secondarySoft,
    "editorGroupHeader.noTabsBackground": p.bg,
    "editorGroupHeader.tabsBackground": dark ? p.bgMuted : "#F0F0F0",
    "editorGroupHeader.tabsBorder": dark ? p.border : "#E3E0CE",
    "editorGutter.addedBackground": p.green,
    "editorGutter.background": p.bg,
    "editorGutter.commentGlyphForeground": p.fgSubtle,
    "editorGutter.deletedBackground": p.red,
    "editorGutter.foldingControlForeground": p.fgMuted,
    "editorGutter.modifiedBackground": p.blue,
    "editorHint.foreground": p.fgMuted,
    "editorHoverWidget.background": p.bgElevated,
    "editorHoverWidget.border": p.border,
    "editorHoverWidget.foreground": p.fg,
    "editorHoverWidget.highlightForeground": p.secondary,
    "editorHoverWidget.statusBarBackground": p.bgMuted,
    "editorIndentGuide.activeBackground1": dark ? "#65737E" : "#A99DB5",
    "editorIndentGuide.background1": dark ? "#37474F80" : "#D8CFBB",
    "editorInfo.foreground": p.blue,
    "editorInlayHint.background": dark ? "#FFFFFF0D" : "#70569712",
    "editorInlayHint.foreground": p.fgMuted,
    "editorInlayHint.parameterBackground": dark ? "#FFFFFF0D" : "#70569712",
    "editorInlayHint.parameterForeground": p.fgMuted,
    "editorInlayHint.typeBackground": dark ? "#80CBC412" : "#B4530912",
    "editorInlayHint.typeForeground": p.secondary,
    "editorLightBulb.foreground": p.yellow,
    "editorLightBulbAi.foreground": p.purple,
    "editorLightBulbAutoFix.foreground": p.blue,
    "editorLineNumber.activeForeground": p.fg,
    "editorLineNumber.dimmedForeground": p.fgSubtle,
    "editorLineNumber.foreground": p.fgSubtle,
    "editorLink.activeForeground": p.blue,
    "editorMarkerNavigation.background": p.bgElevated,
    "editorMarkerNavigationError.background": p.red,
    "editorMarkerNavigationInfo.background": p.blue,
    "editorMarkerNavigationWarning.background": p.yellow,
    "editorMultiCursor.primary.foreground": p.accent,
    "editorMultiCursor.secondary.foreground": p.secondary,
    "editorOverviewRuler.addedForeground": p.green,
    "editorOverviewRuler.border": transparent,
    "editorOverviewRuler.deletedForeground": p.red,
    "editorOverviewRuler.errorForeground": p.red,
    "editorOverviewRuler.modifiedForeground": p.blue,
    "editorOverviewRuler.warningForeground": p.yellow,
    "editor.placeholder.foreground": p.fgSubtle,
    "editorRuler.foreground": p.border,
    "editorStickyScroll.background": p.bg,
    "editorStickyScroll.border": p.border,
    "editorStickyScroll.shadow": dark ? "#00000066" : "#70569724",
    "editorStickyScrollHover.background": p.bgSubtle,
    "editorSuggestWidget.background": p.bgElevated,
    "editorSuggestWidget.border": p.border,
    "editorSuggestWidget.focusHighlightForeground": p.secondary,
    "editorSuggestWidget.foreground": p.fg,
    "editorSuggestWidget.highlightForeground": p.secondary,
    "editorSuggestWidget.selectedBackground": p.bgSubtle,
    "editorSuggestWidget.selectedForeground": p.fg,
    "editorSuggestWidgetStatus.foreground": p.fgMuted,
    "editorUnnecessaryCode.opacity": "#00000080",
    "editorWarning.foreground": p.yellow,
    "editorWhitespace.foreground": dark ? "#65737E" : "#A99F8B",
    "editorWidget.background": p.bgElevated,
    "editorWidget.border": p.border,
    "editorWidget.foreground": p.fg,
    "errorForeground": p.red,
    "extensionBadge.remoteBackground": p.secondary,
    "extensionBadge.remoteForeground": dark ? p.accentContrast : "#FFFFFF",
    "extensionButton.prominentBackground": p.accent,
    "extensionButton.prominentForeground": p.accentContrast,
    "extensionButton.prominentHoverBackground": p.accentHover,
    "focusBorder": p.accent,
    "foreground": p.fg,
    "gitDecoration.addedResourceForeground": dark ? p.green : "#587C0C",
    "gitDecoration.conflictingResourceForeground": dark ? p.orange : "#AD0707",
    "gitDecoration.deletedResourceForeground": dark ? p.red : "#AD0707",
    "gitDecoration.ignoredResourceForeground": dark ? p.fgSubtle : "#8E8E90",
    "gitDecoration.modifiedResourceForeground": dark ? p.blue : "#895503",
    "gitDecoration.renamedResourceForeground": dark ? p.cyan : "#007100",
    "gitDecoration.stageDeletedResourceForeground": dark ? p.red : "#AD0707",
    "gitDecoration.stageModifiedResourceForeground": dark ? p.blue : "#895503",
    "gitDecoration.submoduleResourceForeground": p.purple,
    "gitDecoration.untrackedResourceForeground": dark ? p.green : "#007100",
    "icon.foreground": p.fgMuted,
    "inlineChat.background": p.bgElevated,
    "inlineChat.border": p.border,
    "inlineChat.foreground": p.fg,
    "inlineChat.shadow": dark ? "#00000066" : "#70569726",
    "inlineChatDiff.inserted": inserted,
    "inlineChatDiff.removed": removed,
    "inlineChatInput.background": p.bg,
    "inlineChatInput.border": p.border,
    "inlineChatInput.focusBorder": p.accent,
    "inlineChatInput.placeholderForeground": p.fgSubtle,
    "input.background": p.bgElevated,
    "input.border": p.border,
    "input.foreground": p.fg,
    "input.placeholderForeground": p.fgSubtle,
    "inputOption.activeBackground": p.secondarySoft,
    "inputOption.activeBorder": p.accent,
    "inputOption.activeForeground": p.fg,
    "inputOption.hoverBackground": p.secondarySoft,
    "inputValidation.errorBackground": dangerBackground,
    "inputValidation.errorBorder": p.red,
    "inputValidation.errorForeground": p.fg,
    "inputValidation.infoBackground": infoBackground,
    "inputValidation.infoBorder": p.blue,
    "inputValidation.infoForeground": p.fg,
    "inputValidation.warningBackground": warningBackground,
    "inputValidation.warningBorder": p.yellow,
    "inputValidation.warningForeground": p.fg,
    "keybindingLabel.background": p.bgSubtle,
    "keybindingLabel.border": p.border,
    "keybindingLabel.bottomBorder": p.fgSubtle,
    "keybindingLabel.foreground": p.fg,
    "list.activeSelectionBackground": dark ? "#3B3B40" : "#E8DDF2",
    "list.activeSelectionForeground": p.fg,
    "list.activeSelectionIconForeground": p.accent,
    "list.deemphasizedForeground": p.fgSubtle,
    "list.dropBackground": p.secondarySoft,
    "list.errorForeground": p.red,
    "list.filterMatchBackground": p.secondarySoft,
    "list.focusAndSelectionOutline": p.accent,
    "list.focusBackground": p.bgSubtle,
    "list.focusForeground": p.fg,
    "list.focusHighlightForeground": p.secondary,
    "list.focusOutline": p.accent,
    "list.highlightForeground": p.secondary,
    "list.hoverBackground": dark ? "#FFFFFF0D" : "#70569712",
    "list.hoverForeground": p.fg,
    "list.inactiveFocusBackground": p.bgSubtle,
    "list.inactiveSelectionBackground": dark ? "#343438" : "#EFE7F5",
    "list.inactiveSelectionForeground": p.fg,
    "list.invalidItemForeground": p.orange,
    "list.warningForeground": p.yellow,
    "listFilterWidget.background": p.bgElevated,
    "listFilterWidget.noMatchesOutline": p.red,
    "listFilterWidget.outline": p.accent,
    "listFilterWidget.shadow": dark ? "#00000066" : "#70569726",
    "menu.background": p.bgElevated,
    "menu.border": p.border,
    "menu.foreground": p.fg,
    "menu.selectionBackground": dark ? p.bgSubtle : p.accent,
    "menu.selectionForeground": dark ? p.fg : p.accentContrast,
    "menu.separatorBackground": p.border,
    "menubar.selectionBackground": dark ? p.bgSubtle : "#FFFFFF24",
    "menubar.selectionBorder": transparent,
    "menubar.selectionForeground": chromeForeground,
    "mergeEditor.change.background": inserted,
    "mergeEditor.change.word.background": dark ? "#72A86B55" : "#5A9B5055",
    "mergeEditor.changeBase.background": removed,
    "mergeEditor.changeBase.word.background": dark ? "#C75C6955" : "#C94D6155",
    "mergeEditor.conflict.handled.minimapOverViewRuler": p.fgSubtle,
    "mergeEditor.conflict.handledFocused.border": p.green,
    "mergeEditor.conflict.handledUnfocused.border": p.fgSubtle,
    "mergeEditor.conflict.input1.background": inserted,
    "mergeEditor.conflict.input2.background": removed,
    "mergeEditor.conflict.unhandled.minimapOverViewRuler": p.orange,
    "mergeEditor.conflict.unhandledFocused.border": p.orange,
    "mergeEditor.conflict.unhandledUnfocused.border": p.yellow,
    "mergeEditor.conflictingLines.background": warningBackground,
    "minimap.background": p.bg,
    "minimap.errorHighlight": p.red,
    "minimap.findMatchHighlight": p.accent,
    "minimap.selectionHighlight": p.secondary,
    "minimap.selectionOccurrenceHighlight": p.blue,
    "minimap.warningHighlight": p.yellow,
    "minimapGutter.addedBackground": p.green,
    "minimapGutter.deletedBackground": p.red,
    "minimapGutter.modifiedBackground": p.blue,
    "minimapSlider.activeBackground": dark ? "#FFFFFF4D" : "#7056974D",
    "minimapSlider.background": dark ? "#FFFFFF1F" : "#7056971F",
    "minimapSlider.hoverBackground": dark ? "#FFFFFF33" : "#70569733",
    "notebook.cellBorderColor": p.border,
    "notebook.cellEditorBackground": p.bg,
    "notebook.cellHoverBackground": dark ? "#FFFFFF0D" : "#7056970D",
    "notebook.cellInsertionIndicator": p.accent,
    "notebook.cellStatusBarItemHoverBackground": p.bgSubtle,
    "notebook.cellToolbarSeparator": p.border,
    "notebook.editorBackground": p.bg,
    "notebook.focusedCellBackground": p.bgMuted,
    "notebook.focusedCellBorder": p.accent,
    "notebook.focusedEditorBorder": p.accent,
    "notebook.inactiveFocusedCellBorder": p.border,
    "notebook.outputContainerBackgroundColor": p.bgElevated,
    "notebook.selectedCellBackground": p.bgMuted,
    "notebook.selectedCellBorder": p.secondary,
    "notebook.symbolHighlightBackground": p.secondarySoft,
    "notificationCenter.border": p.border,
    "notificationCenterHeader.background": p.bgMuted,
    "notificationCenterHeader.foreground": p.fg,
    "notificationLink.foreground": p.secondary,
    "notifications.background": p.bgElevated,
    "notifications.border": p.border,
    "notifications.foreground": p.fg,
    "notificationsErrorIcon.foreground": p.red,
    "notificationsInfoIcon.foreground": p.blue,
    "notificationsWarningIcon.foreground": p.yellow,
    "panel.background": p.bg,
    "panel.border": p.border,
    "panel.dropBorder": p.accent,
    "panelInput.border": p.border,
    "panelSection.border": p.border,
    "panelSection.dropBackground": p.secondarySoft,
    "panelSectionHeader.background": p.bgMuted,
    "panelSectionHeader.border": p.border,
    "panelSectionHeader.foreground": p.fg,
    "panelTitle.activeBorder": p.accent,
    "panelTitle.activeForeground": p.fg,
    "panelTitle.inactiveForeground": p.fgSubtle,
    "peekView.border": p.accent,
    "peekViewEditor.background": p.bg,
    "peekViewEditor.matchHighlightBackground": p.secondarySoft,
    "peekViewEditorGutter.background": p.bg,
    "peekViewResult.background": p.bgElevated,
    "peekViewResult.fileForeground": p.fg,
    "peekViewResult.lineForeground": p.fgMuted,
    "peekViewResult.matchHighlightBackground": p.secondarySoft,
    "peekViewResult.selectionBackground": p.bgSubtle,
    "peekViewResult.selectionForeground": p.fg,
    "peekViewTitle.background": p.bgMuted,
    "peekViewTitleDescription.foreground": p.fgMuted,
    "peekViewTitleLabel.foreground": p.fg,
    "pickerGroup.border": p.border,
    "pickerGroup.foreground": p.secondary,
    "problemsErrorIcon.foreground": p.red,
    "problemsInfoIcon.foreground": p.blue,
    "problemsWarningIcon.foreground": p.yellow,
    "profileBadge.background": p.accent,
    "profileBadge.foreground": p.accentContrast,
    "progressBar.background": p.accent,
    "quickInput.background": p.bgElevated,
    "quickInput.foreground": p.fg,
    "quickInputList.focusBackground": p.bgSubtle,
    "quickInputList.focusForeground": p.fg,
    "quickInputList.focusIconForeground": p.accent,
    "quickInputTitle.background": p.bgMuted,
    "sash.hoverBorder": p.accent,
    "scmGraph.foreground1": p.red,
    "scmGraph.foreground2": p.blue,
    "scmGraph.foreground3": p.green,
    "scmGraph.foreground4": p.yellow,
    "scmGraph.foreground5": p.purple,
    "scmGraph.historyItemRefColor": p.secondary,
    "scmGraph.historyItemRemoteRefColor": p.blue,
    "scmGraph.historyItemHoverAdditionsForeground": p.green,
    "scmGraph.historyItemHoverDeletionsForeground": p.red,
    "scrollbar.shadow": dark ? "#00000066" : "#70569724",
    "scrollbarSlider.activeBackground": dark ? "#BFBFBF66" : "#70569766",
    "scrollbarSlider.background": dark ? "#79797966" : "#70569733",
    "scrollbarSlider.hoverBackground": dark ? "#A0A0A080" : "#7056974D",
    "settings.checkboxBackground": p.bgElevated,
    "settings.checkboxBorder": p.border,
    "settings.checkboxForeground": p.fg,
    "settings.dropdownBackground": p.bgElevated,
    "settings.dropdownBorder": p.border,
    "settings.dropdownForeground": p.fg,
    "settings.focusedRowBackground": p.bgMuted,
    "settings.focusedRowBorder": p.accent,
    "settings.headerBorder": p.border,
    "settings.headerForeground": p.fg,
    "settings.modifiedItemIndicator": p.accent,
    "settings.numberInputBackground": p.bgElevated,
    "settings.numberInputBorder": p.border,
    "settings.numberInputForeground": p.fg,
    "settings.rowHoverBackground": p.bgMuted,
    "settings.sashBorder": p.border,
    "settings.textInputBackground": p.bgElevated,
    "settings.textInputBorder": p.border,
    "settings.textInputForeground": p.fg,
    "sideBar.background": dark ? p.bg : p.bgElevated,
    "sideBar.border": p.border,
    "sideBar.dropBackground": p.secondarySoft,
    "sideBar.foreground": p.fg,
    "sideBarSectionHeader.background": dark ? p.bgMuted : "#F0F0F0",
    "sideBarSectionHeader.border": dark ? p.border : "#E3E0CE",
    "sideBarSectionHeader.foreground": dark ? p.fg : "#616161",
    "sideBarTitle.foreground": p.fg,
    "statusBar.background": chrome,
    "statusBar.border": dark ? p.border : p.accentHover,
    "statusBar.debuggingBackground": p.orange,
    "statusBar.debuggingForeground": dark ? p.accentContrast : "#FFFFFF",
    "statusBar.focusBorder": p.accent,
    "statusBar.foreground": chromeForeground,
    "statusBar.noFolderBackground": dark ? p.bgMuted : p.accentHover,
    "statusBar.noFolderForeground": chromeForeground,
    "statusBarItem.activeBackground": dark ? "#FFFFFF1F" : "#FFFFFF33",
    "statusBarItem.compactHoverBackground": dark ? "#FFFFFF1F" : "#FFFFFF33",
    "statusBarItem.errorBackground": p.red,
    "statusBarItem.errorForeground": "#FFFFFF",
    "statusBarItem.focusBorder": p.accentContrast,
    "statusBarItem.hoverBackground": dark ? "#FFFFFF14" : "#FFFFFF26",
    "statusBarItem.prominentBackground": dark ? p.bgSubtle : p.accentHover,
    "statusBarItem.prominentForeground": chromeForeground,
    "statusBarItem.prominentHoverBackground": p.accent,
    "statusBarItem.remoteBackground": p.secondary,
    "statusBarItem.remoteForeground": dark ? p.accentContrast : "#FFFFFF",
    "statusBarItem.warningBackground": p.yellow,
    "statusBarItem.warningForeground": dark ? p.accentContrast : "#FFFFFF",
    "symbolIcon.arrayForeground": p.orange,
    "symbolIcon.booleanForeground": p.orange,
    "symbolIcon.classForeground": p.type,
    "symbolIcon.colorForeground": p.pink,
    "symbolIcon.constantForeground": p.number,
    "symbolIcon.constructorForeground": p.type,
    "symbolIcon.enumeratorForeground": p.type,
    "symbolIcon.enumeratorMemberForeground": p.property,
    "symbolIcon.eventForeground": p.pink,
    "symbolIcon.fieldForeground": p.property,
    "symbolIcon.fileForeground": p.fgMuted,
    "symbolIcon.folderForeground": p.fgMuted,
    "symbolIcon.functionForeground": p.fn,
    "symbolIcon.interfaceForeground": p.type,
    "symbolIcon.keyForeground": p.property,
    "symbolIcon.keywordForeground": p.keyword,
    "symbolIcon.methodForeground": p.fn,
    "symbolIcon.moduleForeground": p.type,
    "symbolIcon.namespaceForeground": p.type,
    "symbolIcon.nullForeground": p.number,
    "symbolIcon.numberForeground": p.number,
    "symbolIcon.objectForeground": p.type,
    "symbolIcon.operatorForeground": p.keyword,
    "symbolIcon.packageForeground": p.type,
    "symbolIcon.propertyForeground": p.property,
    "symbolIcon.referenceForeground": p.cyan,
    "symbolIcon.snippetForeground": p.string,
    "symbolIcon.stringForeground": p.string,
    "symbolIcon.structForeground": p.type,
    "symbolIcon.textForeground": p.fg,
    "symbolIcon.typeParameterForeground": p.type,
    "symbolIcon.unitForeground": p.number,
    "symbolIcon.variableForeground": p.variable,
    "tab.activeBackground": dark ? p.bgMuted : p.bg,
    "tab.activeBorder": dark ? p.accent : "#FF9940",
    "tab.activeBorderTop": dark ? p.accent : transparent,
    "tab.activeForeground": p.fg,
    "tab.border": dark ? p.border : "#E3E0CE",
    "tab.hoverBackground": dark ? p.bgSubtle : "#F5F5F5",
    "tab.hoverBorder": dark ? p.secondary : transparent,
    "tab.hoverForeground": p.fg,
    "tab.inactiveBackground": dark ? p.bgMuted : "#F0F0F0",
    "tab.inactiveForeground": dark ? p.fgSubtle : "#777777",
    "tab.lastPinnedBorder": p.border,
    "tab.selectedBackground": dark ? p.bgSubtle : "#F5F5F5",
    "tab.selectedBorderTop": dark ? p.secondary : transparent,
    "tab.selectedForeground": p.fg,
    "terminal.ansiBlack": dark ? "#2D2D30" : "#3B3347",
    "terminal.ansiBlue": p.blue,
    "terminal.ansiBrightBlack": p.fgSubtle,
    "terminal.ansiBrightBlue": dark ? "#A9C1FF" : "#2E6CCB",
    "terminal.ansiBrightCyan": dark ? "#B2EBF2" : "#00838F",
    "terminal.ansiBrightGreen": dark ? "#D5F4A8" : "#388E3C",
    "terminal.ansiBrightMagenta": dark ? "#E1B7F5" : "#8E4EB3",
    "terminal.ansiBrightRed": dark ? "#FF9CA3" : "#D13B3B",
    "terminal.ansiBrightWhite": dark ? "#FFFFFF" : "#51495A",
    "terminal.ansiBrightYellow": dark ? "#FFE08A" : "#8A6A00",
    "terminal.ansiCyan": p.cyan,
    "terminal.ansiGreen": p.green,
    "terminal.ansiMagenta": p.purple,
    "terminal.ansiRed": p.red,
    "terminal.ansiWhite": p.fg,
    "terminal.ansiYellow": p.yellow,
    "terminal.background": p.bg,
    "terminal.border": p.border,
    "terminal.dropBackground": p.secondarySoft,
    "terminal.findMatchBackground": dark ? "#EF820C66" : "#F5A62380",
    "terminal.findMatchHighlightBackground": p.secondarySoft,
    "terminal.foreground": p.fg,
    "terminal.inactiveSelectionBackground": p.selectionInactive,
    "terminal.selectionBackground": p.selection,
    "terminal.tab.activeBorder": p.accent,
    "terminalCursor.background": p.bg,
    "terminalCursor.foreground": dark ? "#FFCC00" : "#4E342E",
    "testing.coverCountBadgeBackground": p.bgSubtle,
    "testing.coverCountBadgeForeground": p.fg,
    "testing.coveredBackground": inserted,
    "testing.coveredBorder": p.green,
    "testing.coveredGutterBackground": p.green,
    "testing.iconErrored": p.red,
    "testing.iconFailed": p.red,
    "testing.iconPassed": p.green,
    "testing.iconQueued": p.yellow,
    "testing.iconSkipped": p.fgSubtle,
    "testing.iconUnset": p.fgMuted,
    "testing.iconErrored.retired": dark ? "#F0717880" : "#C6282880",
    "testing.iconFailed.retired": dark ? "#F0717880" : "#C6282880",
    "testing.iconPassed.retired": dark ? "#C3E88D80" : "#277A3880",
    "testing.message.error.badgeBackground": p.red,
    "testing.message.error.badgeBorder": p.red,
    "testing.message.error.badgeForeground": "#FFFFFF",
    "testing.message.info.decorationForeground": p.blue,
    "testing.messagePeekBorder": p.accent,
    "testing.messagePeekHeaderBackground": p.bgMuted,
    "testing.peekBorder": p.accent,
    "testing.peekHeaderBackground": p.bgMuted,
    "testing.runAction": p.green,
    "testing.uncoveredBackground": removed,
    "testing.uncoveredBorder": p.red,
    "testing.uncoveredBranchBackground": warningBackground,
    "testing.uncoveredGutterBackground": p.red,
    "textBlockQuote.background": p.bgMuted,
    "textBlockQuote.border": p.accent,
    "textCodeBlock.background": p.bgSubtle,
    "textLink.activeForeground": p.accentHover,
    "textLink.foreground": p.secondary,
    "textPreformat.background": p.bgSubtle,
    "textPreformat.foreground": p.fg,
    "textSeparator.foreground": p.border,
    "titleBar.activeBackground": chrome,
    "titleBar.activeForeground": chromeForeground,
    "titleBar.border": dark ? p.border : p.accentHover,
    "titleBar.inactiveBackground": dark ? p.bgMuted : p.accentHover,
    "titleBar.inactiveForeground": dark ? p.fgSubtle : "#E2DAEA",
    "toolbar.activeBackground": p.bgSubtle,
    "toolbar.hoverBackground": p.bgSubtle,
    "toolbar.hoverOutline": p.accent,
    "tree.indentGuidesStroke": p.border,
    "tree.inactiveIndentGuidesStroke": dark ? "#3B3B3F80" : "#D8CFBB80",
    "walkThrough.embeddedEditorBackground": p.bg,
    "welcomePage.background": p.bg,
    "welcomePage.progress.background": p.bgSubtle,
    "welcomePage.progress.foreground": p.accent,
    "welcomePage.tileBackground": p.bgElevated,
    "welcomePage.tileBorder": p.border,
    "welcomePage.tileHoverBackground": p.bgMuted,
    "widget.border": p.border,
    "widget.shadow": dark ? "#00000066" : "#70569726",
    "window.activeBorder": p.accent,
    "window.inactiveBorder": p.border
  };
}

function syntax(p: Palette): TextMateRule[] {
  if (p.kind === "dark") return darkSyntax(p);
  const s = p.syntax;
  return [
    { name: "Comments", scope: ["comment", "punctuation.definition.comment"], settings: { foreground: s.comment, fontStyle: "" } },
    { name: "Strings", scope: ["string", "string.quoted", "string.template", "punctuation.definition.string"], settings: { foreground: "#1794FAF0" } },
    { name: "Numbers", scope: "constant.numeric", settings: { foreground: s.number } },
    { name: "Built-in constants", scope: "constant.language", settings: { foreground: s.builtInConstant } },
    { name: "User constants", scope: ["constant.character", "constant.other"], settings: { foreground: s.constant } },
    { name: "Keywords", scope: "keyword", settings: { foreground: s.keyword, fontStyle: "bold" } },
    { name: "Storage", scope: ["storage", "storage.modifier"], settings: { foreground: s.storage } },
    { name: "Storage types", scope: "storage.type", settings: { foreground: "#0088FF" } },
    { name: "Operators", scope: ["keyword.operator", "punctuation.separator", "punctuation.accessor"], settings: { foreground: s.punctuation } },
    { name: "Functions", scope: "entity.name.function", settings: { foreground: s.fn } },
    { name: "Library functions", scope: "support.function", settings: { foreground: "#FFCD03" } },
    { name: "Types", scope: ["entity.name.type", "entity.name.class", "entity.name.interface", "support.type", "support.class"], settings: { foreground: s.type } },
    { name: "Variables", scope: ["variable", "variable.other.readwrite"], settings: { foreground: s.variable } },
    { name: "Parameters", scope: "variable.parameter", settings: { foreground: s.parameter } },
    { name: "Properties", scope: ["variable.other.property", "support.type.property-name", "meta.object-literal.key", "entity.other.attribute-name"], settings: { foreground: s.property } },
    { name: "Language variables", scope: ["variable.language", "variable.language.this", "variable.language.super"], settings: { foreground: s.languageVariable } },
    { name: "Tags", scope: ["entity.name.tag", "punctuation.definition.tag"], settings: { foreground: s.tag } },
    { name: "Attributes", scope: ["entity.other.attribute-name", "support.type.property-name.css"], settings: { foreground: s.property } },
    { name: "CSS values", scope: ["support.constant.property-value", "constant.other.color", "support.constant.font-name"], settings: { foreground: s.string } },
    { name: "JSON keys", scope: ["support.type.property-name.json", "string.json support.type.property-name.json"], settings: { foreground: s.property } },
    { name: "Markdown headings", scope: ["markup.heading", "entity.name.section.markdown"], settings: { foreground: s.keyword, fontStyle: "bold" } },
    { name: "Markdown bold", scope: "markup.bold", settings: { foreground: p.fg, fontStyle: "bold" } },
    { name: "Markdown italic", scope: "markup.italic", settings: { foreground: p.fg, fontStyle: "italic" } },
    { name: "Markdown links", scope: ["markup.underline.link", "string.other.link", "meta.link.inline.markdown"], settings: { foreground: p.blue } },
    { name: "Markdown code", scope: ["markup.inline.raw", "markup.fenced_code.block"], settings: { foreground: s.string } },
    { name: "Diff inserted", scope: "markup.inserted", settings: { foreground: p.green } },
    { name: "Diff deleted", scope: "markup.deleted", settings: { foreground: p.red } },
    { name: "Diff changed", scope: "markup.changed", settings: { foreground: p.yellow } },
    { name: "Elixir atoms", scope: ["constant.other.symbol.elixir", "constant.other.symbol.ruby"], settings: { foreground: s.constant } },
    { name: "Elixir module aliases", scope: ["entity.name.type.module.elixir", "support.class.elixir"], settings: { foreground: s.type } },
    { name: "HEEx components", scope: ["entity.name.tag.heex", "support.class.component.heex", "entity.name.tag.html"], settings: { foreground: s.tag } },
    { name: "Invalid", scope: ["invalid", "invalid.illegal"], settings: { foreground: p.red } }
  ];
}

function semantics(p: Palette): Record<string, SemanticStyle> {
  if (p.kind === "dark") return darkSemantics(p);
  const s = p.syntax;
  return {
    "class": s.type,
    "class.declaration": { foreground: s.type, bold: true },
    "comment": { foreground: s.comment, italic: false },
    "decorator": p.pink,
    "enum": s.type,
    "enumMember": s.constant,
    "event": p.pink,
    "function": s.fn,
    "function.declaration": { foreground: s.fn, bold: true },
    "interface": s.type,
    "keyword": s.keyword,
    "label": p.pink,
    "macro": p.purple,
    "method": s.fn,
    "method.declaration": { foreground: s.fn, bold: true },
    "namespace": s.type,
    "number": s.number,
    "operator": s.punctuation,
    "parameter": s.parameter,
    "property": s.property,
    "regexp": p.orange,
    "string": s.string,
    "struct": s.type,
    "type": s.type,
    "typeParameter": s.type,
    "variable": s.variable,
    "variable.readonly": s.constant,
    "*.defaultLibrary": s.type,
    "*.deprecated": { foreground: p.fgSubtle, fontStyle: "strikethrough" }
  };
}

function darkSyntax(p: Palette): TextMateRule[] {
  return [
    { name: "Comments", scope: ["comment", "punctuation.definition.comment"], settings: { foreground: p.comment, fontStyle: "italic" } },
    { name: "Strings", scope: ["string", "string.quoted", "string.template", "punctuation.definition.string"], settings: { foreground: p.string } },
    { name: "Numbers and constants", scope: ["constant.numeric", "constant.language", "constant.character", "constant.other"], settings: { foreground: p.number } },
    { name: "Keywords", scope: ["keyword", "storage.type", "storage.modifier"], settings: { foreground: p.keyword } },
    { name: "Operators", scope: ["keyword.operator", "punctuation.separator", "punctuation.accessor"], settings: { foreground: p.punctuation } },
    { name: "Functions", scope: ["entity.name.function", "support.function", "meta.function-call", "variable.function"], settings: { foreground: p.fn } },
    { name: "Types", scope: ["entity.name.type", "entity.name.class", "entity.name.interface", "support.type", "support.class"], settings: { foreground: p.type } },
    { name: "Variables", scope: ["variable", "variable.other.readwrite", "variable.parameter"], settings: { foreground: p.variable } },
    { name: "Properties", scope: ["variable.other.property", "support.type.property-name", "meta.object-literal.key", "entity.other.attribute-name"], settings: { foreground: p.property } },
    { name: "Language variables", scope: ["variable.language", "variable.language.this", "variable.language.super"], settings: { foreground: p.orange } },
    { name: "Tags", scope: ["entity.name.tag", "punctuation.definition.tag"], settings: { foreground: p.tag } },
    { name: "Attributes", scope: ["entity.other.attribute-name", "support.type.property-name.css"], settings: { foreground: p.property } },
    { name: "CSS values", scope: ["support.constant.property-value", "constant.other.color", "support.constant.font-name"], settings: { foreground: p.string } },
    { name: "JSON keys", scope: ["support.type.property-name.json", "string.json support.type.property-name.json"], settings: { foreground: p.property } },
    { name: "Markdown headings", scope: ["markup.heading", "entity.name.section.markdown"], settings: { foreground: p.keyword, fontStyle: "bold" } },
    { name: "Markdown bold", scope: "markup.bold", settings: { foreground: p.fg, fontStyle: "bold" } },
    { name: "Markdown italic", scope: "markup.italic", settings: { foreground: p.fg, fontStyle: "italic" } },
    { name: "Markdown links", scope: ["markup.underline.link", "string.other.link", "meta.link.inline.markdown"], settings: { foreground: p.blue } },
    { name: "Markdown code", scope: ["markup.inline.raw", "markup.fenced_code.block"], settings: { foreground: p.string } },
    { name: "Diff inserted", scope: "markup.inserted", settings: { foreground: p.green } },
    { name: "Diff deleted", scope: "markup.deleted", settings: { foreground: p.red } },
    { name: "Diff changed", scope: "markup.changed", settings: { foreground: p.yellow } },
    { name: "Elixir atoms", scope: ["constant.other.symbol.elixir", "constant.other.symbol.ruby"], settings: { foreground: p.purple } },
    { name: "Elixir module aliases", scope: ["entity.name.type.module.elixir", "support.class.elixir"], settings: { foreground: p.type } },
    { name: "HEEx components", scope: ["entity.name.tag.heex", "support.class.component.heex", "entity.name.tag.html"], settings: { foreground: p.tag } },
    { name: "Invalid", scope: ["invalid", "invalid.illegal"], settings: { foreground: p.red } }
  ];
}

function darkSemantics(p: Palette): Record<string, SemanticStyle> {
  return {
    "class": p.type,
    "class.declaration": { foreground: p.type, bold: true },
    "comment": { foreground: p.comment, italic: true },
    "decorator": p.pink,
    "enum": p.type,
    "enumMember": p.property,
    "event": p.pink,
    "function": p.fn,
    "function.declaration": { foreground: p.fn, bold: true },
    "interface": p.type,
    "keyword": p.keyword,
    "label": p.pink,
    "macro": p.purple,
    "method": p.fn,
    "method.declaration": { foreground: p.fn, bold: true },
    "namespace": p.type,
    "number": p.number,
    "operator": p.punctuation,
    "parameter": p.variable,
    "property": p.property,
    "regexp": p.orange,
    "string": p.string,
    "struct": p.type,
    "type": p.type,
    "typeParameter": p.type,
    "variable": p.variable,
    "variable.readonly": p.number,
    "*.defaultLibrary": p.cyan,
    "*.deprecated": { foreground: p.fgSubtle, fontStyle: "strikethrough" }
  };
}

export function createTheme(p: Palette): ColorTheme {
  return {
    $schema: "vscode://schemas/color-theme",
    name: p.kind === "dark" ? "Codefolk Dark" : "Codefolk Light",
    type: p.kind,
    semanticHighlighting: true,
    colors: Object.fromEntries(Object.entries(workbench(p)).sort(([a], [b]) => a.localeCompare(b))),
    tokenColors: syntax(p),
    semanticTokenColors: semantics(p)
  };
}
